language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install codecov
# command to run tests
script:
  - coverage run --branch --concurrency=multiprocessing sublist3r_UnitTest.py
  - coverage combine
  - coverage report -m
  - codecov -t 1c0cd6f3-a2e0-413d-a5f4-2e844e0e7bbd

after_success:
  #- codecov -t 1c0cd6f3-a2e0-413d-a5f4-2e844e0e7bbd