language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coverage
# command to run tests
script:
  - coverage run --concurrency=multiprocessing sublist3r_UnitTest.py
  - coverage combine

after_success:
  - codecov